version: '3.8'

services:
  app:
    image: ctse-assignment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/']
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
    restart: unless-stopped
